#!/bin/bash
# set aliases
alias e=exit
alias g=git
alias m=make
alias c=clear
alias b=brew
alias a=atom
alias bc="brew cask"
alias la="ls -laht"
alias rb="source ~/.bash_profile"
alias psa="ps aux | grep --color"
alias fn="find . -iname "
alias rs="rails s -b 0.0.0.0 | grep -vE '(^$|asset)'"
