#!/bin/bash
# set aliases
alias e=exit
alias g=git
alias m=make
alias c="code -r"

alias b=brew
alias bc="brew cask"
alias la="ls -laht"
alias psa="ps aux | grep --color"
alias fn="find . -iname "

alias rb="source ~/.bash_profile"
alias rz="source ~/.zshrc"

# Development
alias rs="rails s -b 0.0.0.0 | grep -vE '(^$|asset)'"
